### ISSUE TITLE
[Bug]: Invalid Config file Line at line 44 Fedora Gnome

### ISSUE THREAD

**Issue by luispereira223** [JaKooLit/Fedora-Hyprland#39]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

installing from this video - https://www.youtube.com/watch?
### Expected Behavior

Top bar to appear but none is appearing

### Actual Behavior

Fresh install with script comamnd and following this youtube tutorial - https://www.youtube.com/watch?v=abp9XkQYETQ
upon logging in to hyprtland for the first time a red bar appears at the top with following error 

"Config error in file /home/user/.config/hypr/UserConfigs/Startup_Apps.conf at line 44: invalid config line"
"Config error in file /home/user/.config/hypr/hyprland.conf at line 12: COnfig error in file /home/user/.config/hypr/UserCOnfigs/Startup_Apps.conf at line 44: invalid config line"

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [Fedora 39]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware]
- Other info: [e.g. mointor resolution 3440x1440]
- Graphics card: rtx 3080 evga ftw3

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Fedora-Hyprland/issues/38

**Comment by nevermore23274** [comment]
So it seems the issue is that you shouldn't be having multiple `#` following one another. Everytime I get an update I'm met with a slew of errors due to this. The header, as well as some UserSettings.conf and other have multiple `#` in a row that tosses up a lot of errors. I usually fix this by just adding a space between the first `#` and the rest, but it also doesn't seem to like the headers so I usually have to remove those.

Is there anything else this could be? That way we're not forced to fix the lines each time an update is pushed? The files I just had to fix were:

- Startup_Apps.conf at line 43
- Laptops.conf at lines 31, 32, 45
- LaptopDisplay.conf at lines 1, 2
- User_Settings.conf at lines 1, 5

Found the reasoning here: https://www.reddit.com/r/hyprland/comments/1b5u8aj/comment/kt7p0wt/
