### ISSUE TITLE
Red screen, system unresponsive after entering password on lock screen

### ISSUE THREAD

**Issue by RedBearAK** [JaKooLit/Fedora-Hyprland#9]
@JaKooLit 

This has happened twice now during testing. The screen locked, and upon entering the password the whole screen turned pure red and the mouse cursor became a thick text cursor. This is in a Boxes VM, and sending the VM key combinations like Ctrl+Alt+Backspace and Ctrl+Alt+Delete have no effect. I have to do a "Force Shutdown" from the Boxes toolbar. 

I've unlocked the screen several other times without the red screen appearing. 

I have no idea what the cause of this problem is, or even which part of the system is having a problem, if it isn't just the lock screen component. Have you heard of this issue? Is there a good place to forward the bug report?

**Comment by JaKooLit** [comment]
swaylock-effects issue

some guys reported to me on my discord....

I didnt change since fedora users have mixed experience

the swaylock-effects that I have set to install is
this which is the old swaylock effects
https://copr.fedorainfracloud.org/coprs/trs-sod/swaylock-effects


somebody tried to install this which is from newer maintainer

https://copr.fedorainfracloud.org/coprs/crashdummy/swaylock-effects



this is now the new who took over
https://github.com/jirutka/swaylock-effects


but if you look at issues
https://github.com/hyprwm/Hyprland/issues/4150





https://github.com/JaKooLit/Hyprland-Dots/issues/52

**Comment by RedBearAK** [comment]
Happened a third time. I thought maybe typing the password more slowly and waiting before hitting Enter would help, and it kind of did seem to prevent the red screen problem. I unlocked several times without seeing it. But then it happened again. Maybe I went too fast that time. 

Not sure how the linked issues are relevant. I don't have a problem with it unlocking itself without entering the password.

**Comment by JaKooLit** [comment]
suggest to report here so his next release will be fix (i hope).... I just install it on a new fedora server type install and no issue with swaylock

https://github.com/jirutka/swaylock-effects/issues

**Comment by RedBearAK** [comment]
Submitted: 

https://github.com/jirutka/swaylock-effects/issues/57

**Comment by JaKooLit** [comment]
dropping swaylock-effects in favor of hyprlock

https://github.com/JaKooLit/Fedora-Hyprland/commit/a0da11fa75bf2dddef1ed51dbd98660fe595d22b
